source "https://rubygems.org"
gem "rspec"
gem "pry"
gem "optimist"
gem "color"
gem "moneta"
gem "rake"
gem "nokogiri"
gem "sqlite3"
gem "vcr"
gem "webmock"
gem "pstore" # no longer part of the stdlib since ruby 4.0
